@isTest
public with sharing class Assignment3Test {
    @isTest static void testMethodOne(){

        Assignment3.methodOne();
    }
    @isTest static void testMethodTwo(){

        Assignment3.methodTwo();
    }
    @isTest static void testMethodThree(){

        Assignment3.methodThree();
    }
    @isTest static void testMethodFour(){

        Assignment3.methodFour();
    }
    @isTest static void testMethodFive(){

        Assignment3.methodFive();
    }
    @isTest static void testMethodSix(){

        Assignment3.methodSix();
    }
    @isTest static void testMethodSeven(){

        Assignment3.methodSeven();
    }
                                                                        
}