@isTest
public class CalculatorAwesomeTest {
	@isTest static void testCallout() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new CalculatorAwesomeCalloutMock());
        // Call the method that invokes a callout
        Double x = 1.0;
        Double y = 2.0;
        Double result = CalculatorAwesome.add(x, y);
        // Verify that a fake result is returned
        System.assertEquals(3.0, result); 
    }
}