@IsTest
private class ContactQRTest {
    /*@isTest static void testgetContactById() {
        Id recordId = createTestRecord();
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/Contact/'+ recordId + '/view?0.source=alohaHeader';
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
        Contact thisContact = ContactQR.getContactById();
        // Verify results
        System.assert(thisContact != null);
        System.assertEquals('Test record', thisContact.Name);
    }
    static Id createTestRecord() {
        // Create test record
        Contact contactTest = new Contact(
        FirstName= 'Test',LastName='record',Email='contacttest@xyz.com',Status__c = 'Active');
        insert contactTest;
        return contactTest.Id;
    } */
}