public class mapAssignment {
    
    	List<String> biharDistricts = new List<String>{'Patna','Lakhisarai', 'Jamui', 'BhagalPur'};
        List<String> uttarPradeshDistricts = new List<String>{'Meerut','Agra', 'Mathura', 'Lucknow'};
        List<String> haryanaDistricts = new List<String>{'Panipat','Sonipat', 'Rohtak', 'Ambala'};
            
Map<String, List<String>> mapOfStateWithCityOfIndia = new Map<String, List<String>>();

     

    

}